### ISSUE TITLE
Docker Images 

### ISSUE THREAD

**Issue by jan-janssen** [materialdigital/pyiron-workflow-mangement#3]
To simplify accessing the individual workflows we could release a couple of docker containers - one for each example workflow - like we do it for pyiron: 
https://github.com/pyiron/docker-stacks

**Comment by max-hassani** [comment]
I think it is impractical if the number of workflows repositories increases, since we would need to maintain a large number of docker images. I guess for testing, we can provide the users two options:
- mybiner link in the readme 
- a Dockerfile in the repo, which could be built and used by the users.

**Comment by jan-janssen** [comment]
I guess that is fine for me as well - we should not spend too much time on this and most likely just having a mybinder link is fine.
